#!/usr/bin/env python3
"""Build the GPLv3 MUSCLE v5.3 source for portable 64-bit Windows.

Platform compatibility is patched, and align honours explicit alphabet flags.
The alignment algorithms and default scoring models remain upstream.
The pristine release archive and generated unified diff remain beside the build.
"""
import argparse
import concurrent.futures
import difflib
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tarfile
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / 'vendor-expanded/muscle-5.3'
TOOLCHAIN = ROOT.parents[1] / 'toolchains/llvm-mingw-20260922-ucrt-ubuntu-22.04-x86_64'

def prepare():
    original = CACHE / 'source/muscle-5.3'
    archive = CACHE / 'muscle-v5.3.tar.gz'
    if hashlib.sha256(archive.read_bytes()).hexdigest() != '74b22a94e630b16015c2bd9ae83aa2be2c2048d3e41f560b2d4a954725c81968':
        raise ValueError('Source archive checksum differs')
    with tarfile.open(archive) as t:
        members = t.getmembers()
        for member in members:
            parts = Path(member.name).parts
            if (not parts or parts[0] != 'muscle-5.3' or
                    Path(member.name).is_absolute() or '..' in parts or
                    not (member.isfile() or member.isdir())):
                raise ValueError('Unsafe source archive member: '+member.name)
        if not original.exists():
            if original.parent.is_symlink():
                raise ValueError('Source extraction directory must not be a link')
            original.parent.mkdir(parents=True, exist_ok=True)
            t.extractall(original.parent, members=members, filter='data')
        for member in members:
            if member.isfile():
                relative = Path(member.name).relative_to('muscle-5.3')
                if (original/relative).read_bytes() != t.extractfile(member).read():
                    raise ValueError('Pristine source was modified: '+str(relative))
    dest = CACHE / 'build-source'
    shutil.copytree(original, dest, dirs_exist_ok=True)
    def edit(name, fn):
        p = dest / 'src' / name
        p.write_text(fn(p.read_text()))
    edit('myutils.h', lambda s: s.replace('typedef long int64;\ntypedef unsigned long uint64;', 'typedef int64_t int64;\ntypedef uint64_t uint64;\nstatic_assert(sizeof(int64) == 8 && sizeof(uint64) == 8, "64-bit integer types required");'))
    def utils(s):
        # These are operating-system tests, not compiler tests. Retain the
        # genuinely MSVC-only debug runtime and fseeko shim guards.
        s = s.replace('#ifdef _MSC_VER', '#ifdef _WIN32').replace('#if _MSC_VER', '#if _WIN32')
        s = s.replace('#ifndef _MSC_VER', '#ifndef _WIN32')
        s = s.replace('#include <crtdbg.h>', '#ifdef _MSC_VER\n#include <crtdbg.h>\n#endif')
        s = s.replace('#ifdef _WIN32\n#include <io.h>\nint fseeko', '#ifdef _MSC_VER\n#include <io.h>\nint fseeko')
        s = s.replace('#ifdef _WIN32\n\tif (IsDebuggerPresent())', '#ifdef _MSC_VER\n\tif (IsDebuggerPresent())')
        s = s.replace('#ifdef _WIN32\n\tprintf("_MSC_VER', '#ifdef _MSC_VER\n\tprintf("_MSC_VER')
        return s
    edit('myutils.cpp', utils)
    edit('align.cpp', lambda s: s.replace('bool IsNucleo = InputSeqs.GuessIsNucleo();', 'if (opt(nt) && opt(amino))\n\t\tDie("Cannot set both -nt and -amino");\n\tbool IsNucleo = opt(nt) ? true : (opt(amino) ? false : InputSeqs.GuessIsNucleo());'))
    edit('align.cpp', lambda s: s.replace('\tMPCFlat M;', '\tProgressLog("Workbench alphabet: %s\\n", IsNucleo ? "nucleotide" : "amino-acid");\n\n\tMPCFlat M;'))
    edit('super5.cpp', lambda s: s.replace('\tSetAlpha(Nucleo ? ALPHA_Nucleo : ALPHA_Amino);', '\tSetAlpha(Nucleo ? ALPHA_Nucleo : ALPHA_Amino);\n\tProgressLog("Workbench alphabet: %s\\n", Nucleo ? "nucleotide" : "amino-acid");'))
    # A truthful local build identifier; upstream gitver.txt is generated by
    # their build script and is absent from the source archive.
    (dest/'src/gitver.txt').write_text('"2cf9d330-workbench1"\n')
    differences = []
    for p in sorted((dest/'src').iterdir()):
        if not p.is_file(): continue
        old = original/'src'/p.name
        a = old.read_text(encoding='latin1') if old.exists() else ''
        b = p.read_text(encoding='latin1')
        if a != b:
            differences.extend(difflib.unified_diff(a.splitlines(True), b.splitlines(True), fromfile='a/src/'+p.name, tofile='b/src/'+p.name))
    (CACHE/'workbench1.patch').write_text(''.join(differences))
    return dest

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--linux',action='store_true')
    parser.add_argument('--jobs',type=int,default=4)
    args=parser.parse_args()
    source=prepare()
    target='linux' if args.linux else 'windows'
    out=CACHE/('build-'+target)
    out.mkdir(exist_ok=True)
    env=os.environ.copy()
    env['LD_LIBRARY_PATH']=str(TOOLCHAIN/'lib')
    env['SOURCE_DATE_EPOCH']='1731288975'
    compiler='g++' if args.linux else str(TOOLCHAIN/'bin/x86_64-w64-mingw32-clang++')
    files=[e.attrib['Include'] for e in ET.parse(source/'src/muscle.vcxproj').iter() if e.tag.endswith('ClCompile') and 'Include' in e.attrib]
    flags=['-std=c++11','-O2','-DNDEBUG','-fopenmp','-Wno-unused-result','-Wno-format','-Wno-deprecated-declarations']
    if not args.linux: flags += ['-DWIN32=1','-D_FILE_OFFSET_BITS=64']
    def compile(name):
        obj=out/(Path(name).stem+'.o')
        command=[compiler,*flags,'-c',str(source/'src'/name),'-o',str(obj)]
        result=subprocess.run(command,env=env,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
        if result.returncode: raise RuntimeError(name+'\n'+result.stdout)
        return obj
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as executor:
        objects=list(executor.map(compile,files))
    binary=out/('muscle' if args.linux else 'muscle.exe')
    command=[compiler,*map(str,objects),'-o',str(binary)]
    if args.linux: command += ['-fopenmp']
    else: command += ['-static',str(TOOLCHAIN/'x86_64-w64-mingw32/lib/libomp.dll.a'),'-lpsapi','-Wl,--no-insert-timestamp']
    subprocess.run(command,env=env,check=True)
    if not args.linux: shutil.copy2(TOOLCHAIN/'x86_64-w64-mingw32/bin/libomp.dll',out/'libomp.dll')
    if not args.linux:
        imports={}
        for name in ('muscle.exe','libomp.dll'):
            report=subprocess.check_output([str(TOOLCHAIN/'bin/llvm-readobj'),'--coff-imports',str(out/name)],env=env,text=True)
            (out/(name+'.imports.txt')).write_text(report)
            imports[name]=re.findall(r'^  Name: (.*)$',report,re.M)
            for dependency in imports[name]:
                if dependency.lower() not in ('kernel32.dll','libomp.dll') and not dependency.lower().startswith('api-ms-win-crt-'):
                    raise ValueError('Unbundled runtime dependency: '+dependency)
        (out/'imports.json').write_text(json.dumps(imports,indent=2)+'\n')
    record={'target':target,'sourceTag':'v5.3','sourceCommit':'2cf9d33078c9a85697e38a6f3ad827e6862420df','patchSha256':hashlib.sha256((CACHE/'workbench1.patch').read_bytes()).hexdigest(),'compiler':subprocess.check_output([compiler,'--version'],env=env,text=True).splitlines()[0],'sourceDateEpoch':env['SOURCE_DATE_EPOCH'],'compileFlags':flags,'linkCommand':command,'sha256':hashlib.sha256(binary.read_bytes()).hexdigest()}
    (out/'build.json').write_text(json.dumps(record,indent=2)+'\n')
    print(json.dumps({'binary':str(binary),'sha256':record['sha256'],'sources':len(files)}))

if __name__=='__main__': main()
