#!/usr/bin/env python3
"""Exercise an exact installed app's references, private RPC and native GUI.

Uses public Ensembl archive release 116 yeast files. The app must be a disposable
extraction: this gate adds references and a local SAMtools indexing run. Windows
uses the app's isolated bundled Python. --skip-gui --skip-analysis permits a
separately labelled Linux live-provider/IPC check, never a Windows gate claim.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import platform
import queue
import shutil
import struct
import subprocess
import sys
import tempfile
import threading
import time
import traceback


# Independent bytes retrieved from the release-pinned upstream objects during
# provider research on 2026-10-05, not generated by the implementation under test.
EXPECTED = {
    "genome": {"bytes": 12360704, "sha256": "35cc97fccb91762c7a1f0f71b4adb1037b143d48b63fbd3b3f8bad45e5afa44c",
               "compressed_bytes": 3784201, "compressed_sha256": "a9953096d6a041a01a4cb5352b0232ee9373bf4c050fb23cb7ae673b2e1bb528"},
    "annotation": {"bytes": 10463408, "sha256": "8c43c98a3a0db24c9e53fd9d460f096c48de0eabefd955fd25d044c948692623",
                   "compressed_bytes": 595453, "compressed_sha256": "253bd4013785b3c85a6a488bd541c12d8264aa4989046c3530d0d9ea2ecc931e"},
    "ncrna": {"bytes": 205371, "sha256": "e875aea40e6bfbf9811b73f30a459439fda48d5165fbaea4c2e4a7859e9c3753",
              "compressed_bytes": 35424, "compressed_sha256": "096064f75fc4c8eaf2845e52dd6d56e1e398f8da434abd8436cfaa2d71a3f604"},
    "cdna": {"bytes": 11714100, "sha256": "0a60e3a655949edbed2e774deae38b896e78e623a45809eafe66d15f7062cf4d",
             "compressed_bytes": 3806426, "compressed_sha256": "3cc5b6bb7ff166cffac5c45317dad7052d06431f43f709ed14b33779702dc6a4"},
    "protein": {"bytes": 5873944, "sha256": "fec10d61996147cbc29ed4587ed0bdeb4e4f5576d66896400b226f2d2d4815a4",
                "compressed_bytes": 2700059, "compressed_sha256": "67ae76c720e52cec167378ec2b8cb5c5929360fc30de31abb37ae1035ef8455c"},
}


def require(condition, message):
    if not condition:
        raise AssertionError(message)


def sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_json(path, value):
    path = Path(path)
    temporary = path.with_name(path.name + ".writing")
    temporary.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    temporary.replace(path)


def checkpoint(report, args, phase):
    report["phase"] = phase
    report["passed"] = len(report["checks"])
    report["updatedUtc"] = datetime.now(timezone.utc).isoformat()
    write_json(args.report, report)
    print(json.dumps({"phase": phase, "passed": report["passed"]}), flush=True)


def stop_process_tree(process):
    """Kill only this gate-owned process and its descendants on failure."""
    if process.poll() is not None:
        return
    if os.name == "nt":
        subprocess.run(["taskkill", "/PID", str(process.pid), "/T", "/F"],
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=15)
    if process.poll() is None:
        process.kill()
    process.wait(timeout=10)


class PrivateHost:
    """A real child interpreter and bounded newline protocol, not a fake service."""
    def __init__(self, root, evidence, name, *, offline=False):
        self.sequence = 0
        self.messages = queue.Queue()
        self.stderr = (evidence / (name + ".stderr.txt")).open("wb")
        host_path = root / "workspace" / "desktop_host.py"
        interpreter = str(root / "runtime" / "python" / "python.exe") if os.name == "nt" else sys.executable
        if offline:
            # Audit hooks deny all Python socket operations before importing
            # production modules. Local listing, binding and indexing must work.
            code = (
                "import sys\n"
                "def deny(event,args):\n"
                " if event.startswith('socket.'): raise RuntimeError('OFFLINE GATE: '+event)\n"
                "sys.addaudithook(deny)\n"
                "sys.path.insert(0,sys.argv[1])\n"
                "from desktop_host import main\n"
                "raise SystemExit(main(['--app-root',sys.argv[2]]))\n"
            )
            command = [interpreter, "-I", "-u", "-c", code, str(host_path.parent), str(root)]
        else:
            command = [interpreter, "-I", "-u", str(host_path), "--app-root", str(root)]
        self.process = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                        stderr=self.stderr, cwd=root)
        self.thread = threading.Thread(target=self._read, daemon=True)
        self.thread.start()

    def _read(self):
        try:
            while True:
                line = self.process.stdout.readline(8 * 1024 * 1024 + 1)
                if not line:
                    self.messages.put(RuntimeError("Private host closed its output."))
                    return
                if len(line) > 8 * 1024 * 1024:
                    raise ValueError("Private host response exceeds protocol limit.")
                self.messages.put(json.loads(line))
        except Exception as exc:
            self.messages.put(exc)

    def call(self, method, params=None, timeout=30):
        self.sequence += 1
        request = {"id": self.sequence, "method": method, "params": params or {}}
        self.process.stdin.write(json.dumps(request, ensure_ascii=True).encode("utf-8") + b"\n")
        self.process.stdin.flush()
        try:
            response = self.messages.get(timeout=timeout)
        except queue.Empty as exc:
            raise TimeoutError("Private host timed out: " + method) from exc
        if isinstance(response, Exception):
            raise response
        require(response.get("id") == self.sequence, "Unexpected private response identity.")
        if not response.get("ok"):
            raise ValueError(method + ": " + str(response.get("error")))
        return response["result"]

    def close(self):
        try:
            if self.process.poll() is None:
                result = self.call("shutdown", timeout=30)
                require(result.get("closed") is True, "Host did not report a clean shutdown.")
                self.process.stdin.close()
                require(self.process.wait(timeout=30) == 0, "Host failed during shutdown.")
        finally:
            if self.process.poll() is None:
                self.process.kill()
                self.process.wait(timeout=10)
            self.stderr.close()


def wait_reference(host, *, timeout=480, expected="completed"):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        state = host.call("references/status")
        operation = state["operation"]
        if not operation.get("active"):
            require(operation.get("status") == expected,
                    "Reference operation ended unexpectedly: " + json.dumps(operation))
            if expected == "completed":
                require(operation.get("success") is True, "Reference operation did not succeed.")
            return state
        time.sleep(.05)
    raise TimeoutError("Reference operation did not finish within the gate's limit.")


def fasta_dictionary(path):
    result = []
    with Path(path).open("rb") as handle:
        for raw in handle:
            line = raw.strip()
            if line.startswith(b">"):
                result.append([line[1:].split()[0].decode("ascii"), 0])
            elif line:
                require(bool(result), "FASTA sequence appeared before its header.")
                result[-1][1] += len(line)
    return result


def run_reference_checks(root, evidence, report, args):
    destination = Path(tempfile.mkdtemp(prefix="reference data ", dir=root.parent))
    sentinel = destination / "keep-me.txt"
    sentinel.write_text("Existing user content must survive cancellation.\n", encoding="utf-8")
    host = PrivateHost(root, evidence, "reference-online-host")
    try:
        initial = host.call("init")
        report["appVersion"] = initial["app_version"]
        require(initial["app_version"] == "0.7.0", "This gate targets the 0.7.0 application contract.")
        state = host.call("references/list")
        old_ids = {record["id"] for record in state["local"]}
        host.call("references/search", {"release": 116, "query": "saccharomyces"})
        state = wait_reference(host)
        require(any(species["id"] == "saccharomyces_cerevisiae" for species in state["species"]),
                "Release 116 discovery did not find Saccharomyces cerevisiae.")
        host.call("references/discover", {"release": 116, "species_id": "saccharomyces_cerevisiae"})
        state = wait_reference(host)
        discovery = state["discovery"]
        write_json(evidence / "discovery.json", discovery)
        require(discovery["release"] == 116 and discovery["assembly"] == "R64-1-1",
                "Discovery resolved a different release or yeast assembly.")
        ids = ["genome", "annotation", "cdna", "ncrna", "protein"]
        require(set(ids) == {item["id"] for item in discovery["files"]},
                "The expected five independently selectable yeast reference products were not discovered.")
        annotation = next(item for item in discovery["files"] if item["id"] == "annotation")
        require(annotation["filename"].endswith("R64-1-1.63.gtf.gz"),
                "Discovery must resolve the archive's actual GTF filename, not guess the release suffix.")
        report["checks"].append("Live release-pinned yeast search and five-product discovery.")
        checkpoint(report, args, report["checks"][-1])
        request = {"selection_id": discovery["selection_id"], "file_ids": ids, "destination": str(destination)}
        host.call("references/download", request)
        deadline = time.monotonic() + 90
        while time.monotonic() < deadline:
            state = host.call("references/status")
            operation = state["operation"]
            require(operation.get("active"), "Cancellation fixture completed or failed before transferring bytes: " + json.dumps(operation))
            if operation.get("bytes", 0) > 0:
                break
            time.sleep(.025)
        else:
            raise TimeoutError("Reference download made no progress for the cancellation gate.")
        report["cancelAtBytes"] = operation["bytes"]
        host.call("references/cancel")
        state = wait_reference(host, expected="cancelled")
        require({record["id"] for record in state["local"]} == old_ids,
                "Cancelled download published a ready reference record.")
        require(list(destination.iterdir()) == [sentinel] and sentinel.read_text(encoding="utf-8").startswith("Existing user content"),
                "Cancellation left partial files or changed existing user content.")
        report["checks"].append("Cancellation after transferred bytes removed only its partial download and published no reference.")
        checkpoint(report, args, report["checks"][-1])
        host.call("references/download", request)
        state = wait_reference(host)
        added = [record for record in state["local"] if record["id"] not in old_ids]
        require(len(added) == 1, "Successful download must publish exactly one local reference record.")
        record = added[0]
        require(record["available"] and record["status"] == "ready", "Completed reference is not locally ready.")
        require(set(ids) == {item["id"] for item in record["files"]}, "A selected reference product was lost.")
        checks = []
        for item in record["files"]:
            path = Path(item["path"])
            require(path.is_file() and path.stat().st_size == item["bytes"], "Downloaded byte size does not match its receipt.")
            require(sha256(path) == item["sha256"], "Downloaded file identity does not match its receipt.")
            require(item["validation"]["gzip_crc"] == "passed" and item["validation"]["provider_bsd_sum"] == "passed",
                    "Download did not verify gzip and provider transfer checks.")
            expected = EXPECTED.get(item["id"])
            if expected:
                for field, value in expected.items():
                    require(item.get(field) == value, "Independent pinned yeast identity differs: " + item["id"] + "/" + field)
            checks.append({"id": item["id"], "bytes": item["bytes"], "sha256": item["sha256"],
                           "compressed_bytes": item["compressed_bytes"], "compressed_sha256": item["compressed_sha256"],
                           "independentPinnedIdentity": expected is not None})
        receipt = Path(record["receipt_path"])
        require(sha256(receipt) == record["receipt_sha256"], "Published provenance receipt hash differs.")
        require(record["release"] == 116 and record["assembly"] == "R64-1-1", "Local receipt lost its archive identity.")
        report["downloads"] = checks
        report["recordId"] = record["id"]
        report["referenceReceiptSha256"] = record["receipt_sha256"]
        write_json(evidence / "reference-receipt.json", json.loads(receipt.read_text(encoding="utf-8")))
        report["checks"].append("Five reference files unpacked atomically with matching receipts; all five independently pinned compressed and expanded hashes agree.")
        checkpoint(report, args, report["checks"][-1])
    finally:
        host.close()

    # Restart a separate actual installed interpreter with socket creation and
    # connection denied. No provider fetch can be hidden inside local reuse.
    host = PrivateHost(root, evidence, "reference-offline-host", offline=True)
    try:
        host.call("init")
        state = host.call("references/list")
        local = next(item for item in state["local"] if item["id"] == record["id"])
        require(local["available"] and local["receipt_sha256"] == record["receipt_sha256"],
                "Offline restart could not rediscover the unchanged local reference.")
        snapshot = host.call("model", {"action": "add_tool", "payload": {"toolId": "bam/reference-index"}})
        targets = host.call("references/targets", {"record_id": record["id"], "file_id": "genome"})["targets"]
        require(len(targets) == 1 and targets[0]["type"] == "reference", "Downloaded genome did not match the existing SAMtools reference input.")
        target = targets[0]
        state = host.call("references/use", {"record_id": record["id"], "file_id": "genome",
                                             "source_id": target["source_id"], "field_id": target["field_id"]})
        genome = next(item for item in record["files"] if item["id"] == "genome")
        graph = state["model"]["graph"]
        source = next(item for item in graph["sources"] if item["id"] == target["source_id"])
        require(source["files"][target["field_id"]] == genome["path"], "Reference use did not bind the selected local file.")
        review = host.call("review")
        require(review["valid"], "Downloaded genome failed the normal analysis review: " + json.dumps(review.get("issues")))
        for token in ("Ensembl archive", "116", "R64-1-1", genome["filename"]):
            require(token in review["methods"], "Planned methods lost reference provenance: " + token)
        (evidence / "methods-preview.txt").write_text(review["methods"], encoding="utf-8")
        report["checks"].append("Socket-denied restart listed local references, matched a typed input and generated reference-aware methods.")
        checkpoint(report, args, report["checks"][-1])
        if args.skip_analysis:
            report["skips"].append("Native SAMtools indexing was explicitly skipped.")
        else:
            output = destination / "analysis results"
            output.mkdir()
            started = host.call("run", {"output_folder": str(output)})
            deadline = time.monotonic() + 180
            while time.monotonic() < deadline:
                run = host.call("run/get", {"run_id": started["run_id"]})
                if run["status"] not in ("preparing", "running", "cancelling"):
                    break
                time.sleep(.1)
            else:
                raise TimeoutError("Native reference indexing did not finish.")
            write_json(evidence / "native-index-run.json", run)
            require(run["status"] == "completed", "Native SAMtools reference indexing failed: " + json.dumps(run))
            report["nativeWindowsExecuted"] = True
            folder = Path(run["folder"])
            indexes = list(folder.rglob("*.fai"))
            require(len(indexes) == 1, "SAMtools must produce exactly one private FASTA index.")
            actual = [[fields[0], int(fields[1])] for line in indexes[0].read_text(encoding="utf-8").splitlines()
                      if (fields := line.split("\t"))]
            expected = fasta_dictionary(genome["path"])
            require(len(expected) == 17 and actual == expected, "Native SAMtools index differs from the independent 17-contig FASTA dictionary.")
            require(sha256(genome["path"]) == EXPECTED["genome"]["sha256"], "Analysis changed the downloaded genome.")
            require(not Path(genome["path"] + ".fai").exists(), "Analysis put an index beside the user's reference instead of its private copy.")
            plan = json.loads((folder / "plan.json").read_text(encoding="utf-8"))
            reference_path = str(Path(genome["path"]).resolve())
            require(plan["references"][reference_path]["file"]["sha256"] == genome["sha256"], "Frozen plan lost the exact downloaded genome identity.")
            require(plan["inputs"][reference_path]["reference"] == plan["references"][reference_path], "Input evidence and frozen reference provenance disagree.")
            frozen = json.loads((folder / "reference-provenance.json").read_text(encoding="utf-8"))
            require(frozen["inputs"] == plan["references"], "Results reference receipt differs from the frozen plan.")
            completed = (folder / "methods-completed.txt").read_text(encoding="utf-8")
            for token in ("Ensembl archive", "116", "R64-1-1", genome["filename"]):
                require(token in completed, "Completed methods lost frozen reference provenance: " + token)
            write_json(evidence / "frozen-reference-provenance.json", frozen)
            (evidence / "methods-completed.txt").write_text(completed, encoding="utf-8")
            report["nativeIndex"] = {"contigs": len(actual), "bases": sum(item[1] for item in actual),
                                      "sha256": sha256(indexes[0]), "dictionary": actual}
            report["checks"].append("Offline native SAMtools indexed all 17 yeast contigs and preserved the reference, frozen identities and completed methods.")
            checkpoint(report, args, report["checks"][-1])
    finally:
        host.close()
    if os.name == "nt":
        sys.path.insert(0, str(root / "workspace"))
        from verify_installation import run_checks
        installation = run_checks(root)
        write_json(evidence / "installation-checks.json", installation)
        require(installation.get("success"), "Released application installation integrity checks failed.")
        report["installation"] = {"passed": installation["passed"], "failed": installation["failed"]}
        report["checks"].append("Installed application and starter pack integrity checks passed after reference use.")
        checkpoint(report, args, report["checks"][-1])


def run_update_checks(root, evidence, report, args):
    """Apply the real update with its own runtime; this does not test its picker."""
    require(os.name == "nt", "Core migration release evidence must execute on native Windows.")
    base, update = args.base_app_root.resolve(), args.update_root.resolve()
    require(base != root and not base.is_relative_to(root) and not update.is_relative_to(base),
            "The update fixture and updater must be separate from the tested starter.")
    require(sha256(args.optional_pack_archive) == "2dd05fece8deb2b0178d8b1bc2b6830f175b3fbc2f5a4d48f9c9023cbfe6775b",
            "Optional reads pack differs from the exact published fixture.")
    require(sha256(args.update_archive) == args.update_sha256.lower(), "Updater archive differs from its declared SHA-256.")
    baseline_manifest = json.loads((base / "manifest.json").read_text(encoding="utf-8"))
    require(baseline_manifest["version"] == "0.6.0", "Updater fixture must begin at application 0.6.0.")
    migration = {"success": False, "baseVersion": "0.6.0", "targetVersion": report["appVersion"],
                 "baseArchiveSha256": "16fa802304c734b5721d838ff38b7e90ed36ccfc185a22239859cc3762af695a",
                 "updateArchiveSha256": sha256(args.update_archive),
                 "optionalPackArchiveSha256": sha256(args.optional_pack_archive),
                 "scope": "Actual native Windows updater CLI using its private runtime; native folder-picker interaction is not exercised."}
    report["coreUpdate"] = migration
    checkpoint(report, args, "core-update: import optional pack and save baseline settings")
    host = PrivateHost(base, evidence, "update-baseline-host", offline=True)
    try:
        initial = host.call("init")
        require(initial["app_version"] == "0.6.0", "The exact baseline private host did not report 0.6.0.")
        host.call("packs/import", {"path": str(args.optional_pack_archive.resolve())})
        deadline = time.monotonic() + 120
        while time.monotonic() < deadline:
            state = host.call("packs/status")
            operation = state["operation"]
            if not operation.get("active"):
                require(operation.get("status") == "completed" and operation.get("success"),
                        "The baseline's native optional-pack import failed: " + json.dumps(operation))
                break
            time.sleep(.05)
        else:
            raise TimeoutError("Baseline optional-pack import did not finish.")
        state = host.call("state")
        reads = next(tool for tool in state["catalog"]["tools"].values() if tool.get("packId") == "reads")
        state = host.call("model", {"action": "add_tool", "payload": {"toolId": reads["id"]}})
        node = state["graph"]["nodes"][-1]
        optional_pin = node["pin"]
        host.call("save", {"kind": "preset", "name": "Preserve optional reads settings", "nodeId": node["id"]})
        host.call("model", {"action": "remove_step", "payload": {"nodeId": node["id"]}})
        state = host.call("model", {"action": "add_tool", "payload": {"toolId": "bam/reference-index"}})
        index_node = state["graph"]["nodes"][-1]
        host.call("model", {"action": "use_output", "payload": {"toolId": "bam/reference-index", "ref": index_node["id"] + "::reference"}})
        host.call("save", {"kind": "pipeline", "name": "Preserve connected pinned pipeline"})
    finally:
        host.close()
    migration["nativeOptionalPackImport"] = True
    reference_data = base / "user-data" / "references"
    reference_data.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(root / "user-data" / "references" / "library.json", reference_data / "library.json")
    (reference_data / "user-reference.fa").write_text(">preserved_user_sequence\nACGTACGT\n", encoding="utf-8")
    (base / "results").mkdir(exist_ok=True)
    (base / "results" / "existing-result.txt").write_text("An existing local analysis must remain unchanged.\n", encoding="utf-8")
    preserved = {path.relative_to(base).as_posix(): sha256(path)
                 for folder in ("packs", "user-data", "results")
                 for path in sorted((base / folder).rglob("*")) if path.is_file()}
    saved_before = json.loads((base / "user-data" / "saved.json").read_text(encoding="utf-8"))
    require(len(saved_before["presets"]) == 1 and len(saved_before["pipelines"]) == 1,
            "Baseline did not create separate settings and a pinned pipeline.")
    require(saved_before["presets"][0]["pin"] == optional_pin, "Optional preset did not save its exact version/manifest pin.")
    command = [str(update / "runtime" / "python" / "python.exe"), "-I",
               str(update / "update" / "apply_workspace_update.py"), "--app-root", str(base)]
    for attempt in ("install", "repeat"):
        checkpoint(report, args, "core-update: " + attempt)
        completed = subprocess.run(command, cwd=update, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=180)
        (evidence / ("update-" + attempt + ".stdout.txt")).write_bytes(completed.stdout)
        (evidence / ("update-" + attempt + ".stderr.txt")).write_bytes(completed.stderr)
        require(completed.returncode == 0, "Native core updater failed: " + completed.stderr.decode("utf-8", "replace"))
        result, _ = json.JSONDecoder().raw_decode(completed.stdout.decode("utf-8").lstrip())
        require(result["status"] == ("installed" if attempt == "install" else "already-installed"),
                "Unexpected core updater transaction status: " + json.dumps(result))
        migration[attempt] = result
    checkpoint(report, args, "core-update: verify exact core and preserved user files")
    require((base / "manifest.json").read_bytes() == (root / "manifest.json").read_bytes(),
            "Updated core manifest is not byte-identical to the exact new starter.")
    for item in json.loads((root / "manifest.json").read_text(encoding="utf-8"))["files"]:
        path = base / item["path"]
        require(path.is_file() and path.stat().st_size == item["bytes"] and sha256(path) == item["sha256"],
                "Updated core file differs from the exact starter: " + item["path"])
    after = {path.relative_to(base).as_posix(): sha256(path)
             for folder in ("packs", "user-data", "results")
             for path in sorted((base / folder).rglob("*")) if path.is_file()}
    # The legacy coordination lock is created by every updater, including the
    # released 0.6 implementation. It is not an analysis/settings replacement.
    # All pre-existing files must remain byte-identical; the only permitted new
    # file is that exact one-byte lock. Retain differences for actionable CI.
    changes = {name: {"before": digest, "after": after.get(name)}
               for name, digest in preserved.items() if after.get(name) != digest}
    additions = {name: digest for name, digest in after.items() if name not in preserved}
    migration["preservationChanges"] = changes
    migration["preservationAdditions"] = additions
    require(not changes and all(name == "user-data/session.lock" and
                                digest == hashlib.sha256(b"\0").hexdigest()
                                for name, digest in additions.items()),
            "Core migration changed user files or added unexpected data: " +
            json.dumps({"changed": changes, "added": additions}))
    checkpoint(report, args, "core-update: restart updated host offline and reload saved pins")
    host = PrivateHost(base, evidence, "updated-offline-host", offline=True)
    try:
        state = host.call("init")
        require(state["app_version"] == report["appVersion"], "Updated private Python host did not start the new app version.")
        references = host.call("references/list")
        require(any(record["id"] == report["recordId"] and record["available"] for record in references["local"]),
                "Updated application did not retain the local reference library offline.")
        state = host.call("model", {"action": "add_tool", "payload": {
            "toolId": saved_before["presets"][0]["tool"], "pin": optional_pin}})
        host.call("load", {"kind": "preset", "id": saved_before["presets"][0]["id"],
                           "node_id": state["graph"]["nodes"][-1]["id"]})
        state = host.call("state")
        require(state["graph"]["nodes"][-1]["pin"] == optional_pin,
                "Updated application changed the saved optional pack/version pin.")
        state = host.call("load", {"kind": "pipeline", "id": saved_before["pipelines"][0]["id"]})
        require([node["pin"] for node in state["graph"]["nodes"]]
                == [node["pin"] for node in saved_before["pipelines"][0]["graph"]["nodes"]],
                "Updated application changed the saved pipeline pins.")
    finally:
        host.close()
    migration.update(success=True, preservedFiles=len(preserved), optionalPin=optional_pin,
                     coreManifestSha256=sha256(base / "manifest.json"), offlineRestart=True)
    write_json(evidence / "native-core-update.json", migration)
    report["checks"].append("Native 0.6.0-to-0.7.0 core migration and idempotent repeat preserved optional packs, saved pins, references and results; updated private host reused them offline.")
    checkpoint(report, args, report["checks"][-1])


def reference_control_geometry(rows, *, local=False):
    """Validate independently observed Win32 bounds, not layout constants."""
    by_id = {row["id"]: row for row in rows}
    pairs = ([(612, 608), (608, 613), (608, 614), (608, 615)] if local else
             [(605, 606), (606, 607), (607, 608),
              (608, 609), (608, 610), (608, 611)])
    gaps = []
    for upper, lower in pairs:
        require(upper in by_id and lower in by_id,
                "Native layout check is missing controls: " + str((upper, lower)))
        upper_bounds, lower_bounds = by_id[upper]["bounds"], by_id[lower]["bounds"]
        require(upper_bounds[2] > upper_bounds[0] and upper_bounds[3] > upper_bounds[1]
                and lower_bounds[2] > lower_bounds[0] and lower_bounds[3] > lower_bounds[1],
                "Native reference control has empty or inverted bounds.")
        gap = lower_bounds[1] - upper_bounds[3]
        require(gap > 0, "Native reference controls overlap or touch: " +
                json.dumps({"upper": upper, "lower": lower, "gapPixels": gap,
                            "upperBounds": upper_bounds, "lowerBounds": lower_bounds}))
        gaps.append({"upper": upper, "lower": lower, "gapPixels": gap})
    return gaps


def gui_smoke(root, evidence):
    """Real Win32 launch, button, child controls, resize and captured pixels."""
    import ctypes
    from ctypes import wintypes
    user = ctypes.WinDLL("user32", use_last_error=True)
    gdi = ctypes.WinDLL("gdi32", use_last_error=True)
    user.SetThreadDpiAwarenessContext.argtypes = [ctypes.c_void_p]
    user.SetThreadDpiAwarenessContext.restype = ctypes.c_void_p
    previous_dpi_context = user.SetThreadDpiAwarenessContext(ctypes.c_void_p(-4))
    user.GetDpiForWindow.argtypes = [wintypes.HWND]
    user.GetDpiForWindow.restype = wintypes.UINT
    callback_type = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)
    user.EnumWindows.argtypes = [callback_type, wintypes.LPARAM]
    user.EnumChildWindows.argtypes = [wintypes.HWND, callback_type, wintypes.LPARAM]
    user.GetWindowThreadProcessId.argtypes = [wintypes.HWND, ctypes.POINTER(wintypes.DWORD)]
    user.GetWindowTextW.argtypes = [wintypes.HWND, wintypes.LPWSTR, ctypes.c_int]
    user.GetClassNameW.argtypes = [wintypes.HWND, wintypes.LPWSTR, ctypes.c_int]
    user.GetDlgCtrlID.argtypes = [wintypes.HWND]
    user.GetDlgItem.argtypes = [wintypes.HWND, ctypes.c_int]
    user.GetDlgItem.restype = wintypes.HWND
    user.IsWindowVisible.argtypes = [wintypes.HWND]
    user.GetWindowRect.argtypes = [wintypes.HWND, ctypes.POINTER(wintypes.RECT)]
    user.GetClientRect.argtypes = [wintypes.HWND, ctypes.POINTER(wintypes.RECT)]
    user.SendMessageTimeoutW.argtypes = [wintypes.HWND, wintypes.UINT, wintypes.WPARAM,
                                       wintypes.LPARAM, wintypes.UINT, wintypes.UINT,
                                       ctypes.POINTER(ctypes.c_size_t)]
    user.SendMessageTimeoutW.restype = wintypes.LPARAM
    user.PostMessageW.argtypes = [wintypes.HWND, wintypes.UINT, wintypes.WPARAM, wintypes.LPARAM]
    user.MoveWindow.argtypes = [wintypes.HWND, ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.c_int, wintypes.BOOL]
    user.GetDC.argtypes = [wintypes.HWND]
    user.GetDC.restype = wintypes.HDC
    user.ReleaseDC.argtypes = [wintypes.HWND, wintypes.HDC]
    user.PrintWindow.argtypes = [wintypes.HWND, wintypes.HDC, wintypes.UINT]
    gdi.CreateCompatibleDC.argtypes = [wintypes.HDC]
    gdi.CreateCompatibleDC.restype = wintypes.HDC
    gdi.CreateCompatibleBitmap.argtypes = [wintypes.HDC, ctypes.c_int, ctypes.c_int]
    gdi.CreateCompatibleBitmap.restype = wintypes.HBITMAP
    gdi.SelectObject.argtypes = [wintypes.HDC, wintypes.HANDLE]
    gdi.SelectObject.restype = wintypes.HANDLE
    gdi.DeleteObject.argtypes = [wintypes.HANDLE]
    gdi.DeleteDC.argtypes = [wintypes.HDC]
    gdi.GetDIBits.argtypes = [wintypes.HDC, wintypes.HBITMAP, wintypes.UINT, wintypes.UINT,
                            ctypes.c_void_p, ctypes.c_void_p, wintypes.UINT]

    def progress(phase, **details):
        value = {"phase": phase, "updatedUtc": datetime.now(timezone.utc).isoformat(), **details}
        write_json(evidence / "gui-progress.json", value)
        with (evidence / "gui-events.jsonl").open("a", encoding="utf-8") as events:
            events.write(json.dumps(value, ensure_ascii=False) + "\n")
        print(json.dumps({"guiPhase": phase, **details}), flush=True)

    def send(hwnd, message, wparam=0, lparam=0):
        result = ctypes.c_size_t()
        ctypes.set_last_error(0)
        require(user.SendMessageTimeoutW(hwnd, message, wparam, lparam, 0x0003, 5000,
                                        ctypes.byref(result)),
                "Native GUI message timed out or failed: message=" + hex(message) +
                " hwnd=" + str(hwnd) + " winerror=" + str(ctypes.get_last_error()))
        return result.value

    def text(hwnd, class_name=False):
        buffer = ctypes.create_unicode_buffer(1024)
        (user.GetClassNameW if class_name else user.GetWindowTextW)(hwnd, buffer, len(buffer))
        return buffer.value

    def windows(pid):
        found = []
        @callback_type
        def each(hwnd, _):
            owner = wintypes.DWORD()
            user.GetWindowThreadProcessId(hwnd, ctypes.byref(owner))
            if owner.value == pid and user.IsWindowVisible(hwnd):
                found.append(hwnd)
            return True
        user.EnumWindows(each, 0)
        return found

    def find_window(pid, title, seconds=30):
        deadline = time.monotonic() + seconds
        while time.monotonic() < deadline:
            for hwnd in windows(pid):
                if text(hwnd) == title:
                    return hwnd
            time.sleep(.1)
        raise TimeoutError("Native window was not created: " + title)

    def controls(hwnd):
        found = []
        @callback_type
        def each(child, _):
            if user.IsWindowVisible(child):
                rect = wintypes.RECT()
                user.GetWindowRect(child, ctypes.byref(rect))
                found.append({"id": user.GetDlgCtrlID(child), "class": text(child, True),
                              "text": text(child), "bounds": [rect.left, rect.top, rect.right, rect.bottom]})
            return True
        user.EnumChildWindows(hwnd, each, 0)
        return found

    def capture(hwnd, path):
        progress("capture pixels", capture=path.name)
        rect = wintypes.RECT()
        user.GetWindowRect(hwnd, ctypes.byref(rect))
        width, height = rect.right - rect.left, rect.bottom - rect.top
        dc = user.GetDC(hwnd)
        memory = gdi.CreateCompatibleDC(dc)
        bitmap = gdi.CreateCompatibleBitmap(dc, width, height)
        old = gdi.SelectObject(memory, bitmap)
        try:
            require(user.PrintWindow(hwnd, memory, 0), "Native window capture failed.")
            header = struct.pack("<IiiHHIIiiII", 40, width, -height, 1, 32, 0, width * height * 4, 0, 0, 0, 0)
            info = ctypes.create_string_buffer(header + bytes(1024))
            pixels = ctypes.create_string_buffer(width * height * 4)
            gdi.SelectObject(memory, old)
            require(gdi.GetDIBits(memory, bitmap, 0, height, pixels, info, 0) == height,
                    "Native screenshot pixel read failed.")
            raw = pixels.raw
            require(len(set(raw[::4])) > 4, "Native window capture appears blank.")
            path.write_bytes(struct.pack("<2sIHHI", b"BM", 54 + len(raw), 0, 0, 54) + header + raw)
            return {"path": path.name, "width": width, "height": height, "sha256": sha256(path)}
        finally:
            gdi.SelectObject(memory, old)
            gdi.DeleteObject(bitmap)
            gdi.DeleteDC(memory)
            user.ReleaseDC(hwnd, dc)

    progress("launch native desktop")
    process = subprocess.Popen([str(root / "NativeWorkbench.exe")], cwd=root)
    main = None
    try:
        progress("wait for main window", pid=process.pid)
        main = find_window(process.pid, "Native Workbench")
        progress("open References", pid=process.pid, windows=[
            {"hwnd": hwnd, "title": text(hwnd), "class": text(hwnd, True)}
            for hwnd in windows(process.pid)])
        deadline = time.monotonic() + 30
        while time.monotonic() < deadline:
            # The command is dispatched to the same handler as clicking References.
            require(user.PostMessageW(main, 0x0111, 403, 0),
                    "Could not post the native References command.")  # WM_COMMAND, MANAGE_REFERENCES
            found = [h for h in windows(process.pid) if text(h, True) == "WorkbenchReferences070"]
            if found:
                break
            time.sleep(.1)
        require(bool(found), "References toolbar command did not open its native window.")
        ref = found[0]
        progress("wait for local reference library to populate")
        deadline = time.monotonic() + 15
        rows = 0
        while time.monotonic() < deadline:
            local_list = user.GetDlgItem(ref, 612)
            rows = send(local_list, 0x1004, 0, 0) if local_list else 0
            if rows >= 5:
                break
            time.sleep(.1)
        require(rows >= 5, "The native reference window did not finish loading its local library.")
        progress("inspect normal References controls")
        normal = controls(ref)
        progress("normal References controls discovered", controls=normal)
        normal_geometry = reference_control_geometry(normal)
        require({601, 602, 603, 604, 605, 606, 607, 609, 610, 611, 619}
                <= {row["id"] for row in normal}, "References window is missing native controls.")
        result = {"launched": True, "pid": process.pid, "class": text(ref, True), "title": text(ref),
                  "normalControls": normal, "normalGeometry": normal_geometry,
                  "captures": [capture(ref, evidence / "references-normal.bmp")],
                  "scope": "Automated Win32 launch, local-library loading, queued tab input, observed control non-overlap at normal/minimum size, resize and pixel capture; human usability acceptance remains separate."}
        dpi = user.GetDpiForWindow(ref) or 96
        result["dpi"] = dpi
        progress("resize References to minimum")
        require(user.MoveWindow(ref, 10, 10, round(820 * dpi / 96), round(680 * dpi / 96), True),
                "Native reference window resize failed.")
        time.sleep(.3)
        result["minimumControls"] = controls(ref)
        result["minimumGeometry"] = reference_control_geometry(result["minimumControls"])
        progress("minimum References geometry checked", geometry=result["minimumGeometry"],
                 controls=result["minimumControls"])
        result["captures"].append(capture(ref, evidence / "references-minimum.bmp"))
        # Send an ordinary right-arrow key to the real native tab control. It
        # generates its own in-process notification; never pass cross-process
        # pointers through WM_NOTIFY or list-view messages.
        tab = user.GetDlgItem(ref, 601)
        progress("select Downloaded tab")
        # Queue normal key input on the target UI thread. Synchronously sending
        # a key from another process can deadlock focus/notification handling.
        require(user.PostMessageW(tab, 0x0100, 0x27, 1),
                "Could not queue the native tab key-down event.")  # WM_KEYDOWN, VK_RIGHT
        require(user.PostMessageW(tab, 0x0101, 0x27, 0xC0000001),
                "Could not queue the native tab key-up event.")
        deadline = time.monotonic() + 15
        while time.monotonic() < deadline:
            local_list = user.GetDlgItem(ref, 612)
            rows = send(local_list, 0x1004, 0, 0)  # LVM_GETITEMCOUNT; also proves UI responsiveness
            local_controls = controls(ref)
            visible = {row["id"] for row in local_controls}
            if {612, 613, 614, 615} <= visible and rows >= 5:
                break
            time.sleep(.1)
        progress("inspect Downloaded tab", selectedTab=send(tab, 0x130B, 0, 0),
                 rows=rows, controls=local_controls)  # TCM_GETCURSEL
        require({612, 613, 614, 615} <= visible and rows >= 5,
                "Downloaded native tab did not show the five local reference products.")
        result["downloadedControls"] = local_controls
        result["downloadedGeometry"] = reference_control_geometry(local_controls, local=True)
        result["downloadedRows"] = rows
        result["captures"].append(capture(ref, evidence / "references-downloaded-minimum.bmp"))
        progress("close References and desktop")
        send(ref, 0x0111, 619, 0)
        time.sleep(.1)
        require(not any(text(h, True) == "WorkbenchReferences070" for h in windows(process.pid)),
                "Closing References left its visible window open.")
        user.PostMessageW(main, 0x0010, 0, 0)  # WM_CLOSE
        require(process.wait(timeout=30) == 0, "Native desktop failed to close cleanly.")
        result["closedCleanly"] = True
        progress("completed")
        return result
    finally:
        stop_process_tree(process)
        host_log = root / "user-data" / "desktop-host.stderr.txt"
        if host_log.is_file():
            shutil.copyfile(host_log, evidence / "gui-desktop-host.stderr.txt")
        if previous_dpi_context:
            user.SetThreadDpiAwarenessContext(previous_dpi_context)


def gui_smoke_bounded(root, evidence):
    """Bound even synchronous Win32 painting/window enumeration in a worker."""
    worker_report = evidence / "gui-worker.json"
    command = [sys.executable, "-I", "-u", str(Path(__file__).resolve()), "--gui-worker",
               "--app-root", str(root), "--report", str(worker_report)]
    with (evidence / "gui-worker.stderr.txt").open("wb") as stderr:
        process = subprocess.Popen(command, stderr=stderr)
        try:
            process.wait(timeout=180)
        except subprocess.TimeoutExpired as exc:
            progress_file = evidence / "gui-progress.json"
            last = json.loads(progress_file.read_text(encoding="utf-8")) if progress_file.is_file() else {}
            raise TimeoutError("Native GUI smoke exceeded 180 seconds; last phase: " + json.dumps(last)) from exc
        finally:
            stop_process_tree(process)
            host_log = root / "user-data" / "desktop-host.stderr.txt"
            if host_log.is_file():
                shutil.copyfile(host_log, evidence / "gui-desktop-host.stderr.txt")
    require(worker_report.is_file(), "Native GUI worker exited without its result report.")
    result = json.loads(worker_report.read_text(encoding="utf-8"))
    require(process.returncode == 0 and result.get("success"),
            "Native GUI smoke failed: " + json.dumps(result))
    return result["gui"]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app-root", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--source-commit", default="unrecorded")
    parser.add_argument("--asset-sha256", default="unrecorded")
    parser.add_argument("--asset-name", default="unrecorded")
    parser.add_argument("--release-tag", default="unrecorded")
    parser.add_argument("--skip-gui", action="store_true")
    parser.add_argument("--skip-analysis", action="store_true")
    parser.add_argument("--base-app-root", type=Path)
    parser.add_argument("--update-root", type=Path)
    parser.add_argument("--update-archive", type=Path)
    parser.add_argument("--update-sha256")
    parser.add_argument("--optional-pack-archive", type=Path)
    parser.add_argument("--gui-worker", action="store_true", help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = args.app_root.resolve()
    args.report = args.report.resolve()
    evidence = args.report.parent
    evidence.mkdir(parents=True, exist_ok=True)
    if args.gui_worker:
        result = {"success": False}
        try:
            require(os.name == "nt", "The GUI worker requires native Windows.")
            result["gui"] = gui_smoke(root, evidence)
            result["success"] = True
        except Exception as exc:
            result.update(error=str(exc), traceback=traceback.format_exc())
        write_json(args.report, result)
        return 0 if result["success"] else 1
    report = {"schema": 1, "success": False, "startedUtc": datetime.now(timezone.utc).isoformat(),
              "platform": platform.platform(), "python": sys.version, "appRoot": str(root),
              "nativeWindowsHost": os.name == "nt", "nativeWindowsExecuted": False,
              "sourceCommit": args.source_commit, "assetSha256": args.asset_sha256,
              "assetName": args.asset_name, "releaseTag": args.release_tag,
              "gateSha256": sha256(__file__), "checks": [], "skips": []}
    host = None
    try:
        require(os.name == "nt" or args.skip_gui and args.skip_analysis,
                "Linux checks must explicitly skip GUI and native analysis; this is a Windows release gate.")
        require((root / "workspace" / "desktop_host.py").is_file(), "Expected an extracted application.")
        if os.name == "nt":
            require(Path(sys.executable).resolve() == (root / "runtime" / "python" / "python.exe").resolve(),
                    "The native release gate must use this application's bundled isolated Python.")
        report["appFiles"] = {str(path.relative_to(root)): sha256(path) for path in sorted((root / "workspace").glob("*.py"))}
        # Implementation-specific live assertions are below; failures retain the
        # exact stage and traceback rather than reporting a successful skipped gate.
        checkpoint(report, args, "references: live discovery, downloads, cancellation and offline native reuse")
        run_reference_checks(root, evidence, report, args)
        checkpoint(report, args, "references: completed")
        update_options = (args.base_app_root, args.update_root, args.update_archive, args.update_sha256, args.optional_pack_archive)
        require(not any(update_options) or all(update_options), "The updater gate needs its base app, updater folder/archive/hash and exact optional pack archive.")
        if all(update_options):
            run_update_checks(root, evidence, report, args)
            checkpoint(report, args, "core-update: completed")
        else:
            report["skips"].append("Optional native core updater gate was not requested.")
        if args.skip_gui:
            report["skips"].append("Native GUI smoke was explicitly skipped.")
        else:
            checkpoint(report, args, "gui: launch bounded 180-second native smoke")
            report["gui"] = gui_smoke_bounded(root, evidence)
            report["checks"].append("Native app opened References, displayed five local files, kept controls separate at normal/minimum size and closed cleanly.")
            checkpoint(report, args, report["checks"][-1])
        report["success"] = True
        checkpoint(report, args, "completed")
    except Exception as exc:
        report["error"] = str(exc)
        report["traceback"] = traceback.format_exc()
    finally:
        if host is not None:
            host.close()
        report["completedUtc"] = datetime.now(timezone.utc).isoformat()
        report["passed"] = len(report["checks"])
        write_json(args.report, report)
    print(json.dumps({"success": report["success"], "passed": report["passed"],
                      "nativeWindowsHost": report["nativeWindowsHost"],
                      "nativeWindowsExecuted": report["nativeWindowsExecuted"],
                      "skips": report["skips"], "report": str(args.report)}))
    return 0 if report["success"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
