#!/usr/bin/env python3
"""Package the native 0.5.2 tool expansion from an intact 0.5.1 release."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import sys

import package_desktop as desktop

SOURCE = Path(__file__).resolve().parents[1]
VERSION = '0.5.2'
PACKS = ('seqkit', 'vsearch', 'muscle')
MODULES = (*desktop.RUNTIME_MODULES, 'pack_checks.py')


def stage(base, app):
    base, app = Path(base).resolve(), Path(app).resolve()
    desktop.require(not app.exists(), 'Choose a new target directory')
    desktop.require(not app.is_relative_to(base) and not base.is_relative_to(app), 'Baseline and target overlap')
    manifest = json.loads((base/'manifest.json').read_text(encoding='utf-8'))
    desktop.require(manifest.get('version') == '0.5.1' and manifest.get('interface') == 'native-win32', 'Expected native 0.5.1 baseline')
    # Verify before copying, including the scientific tools and complete source.
    for item in manifest['files']:
        path = base/item['path']
        desktop.require(path.is_file() and not path.is_symlink() and path.stat().st_size == item['bytes'] and desktop.sha(path) == item['sha256'], 'Baseline differs: '+item['path'])
    app.mkdir(parents=True)
    for item in manifest['files']:
        if item['path'].startswith('source/'):
            continue
        destination = app/item['path']
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(base/item['path'], destination)
    for name in MODULES:
        shutil.copy2(SOURCE/'workspace'/name, app/'workspace'/name)
    shutil.copy2(SOURCE/'build/desktop/DesktopWorkbench.exe', app/'NativeWorkbench.exe')
    for identity in PACKS:
        name = identity+'-'+VERSION
        shutil.copytree(SOURCE/'packs'/name, app/'packs'/name)
    shutil.copytree(SOURCE/'workspace/release-expansion', app, dirs_exist_ok=True)
    shutil.copy2(SOURCE/'README-0.5.2.txt', app/'docs/BUILD-0.5.2.txt')
    for path in (SOURCE/'validation').glob('*0.5.2*'):
        if path.is_file():
            shutil.copy2(path, app/'validation'/path.name)
    desktop.verify_fixed_packs(app)
    sys.path.insert(0, str(SOURCE/'workspace'))
    from catalog import load_catalog
    catalog = load_catalog(app)
    for identity in PACKS:
        desktop.require(any(p['id'] == identity and p['version'] == VERSION for p in catalog['packs']), 'Missing expansion pack '+identity)
    return catalog


def finish(base, app, output=None):
    base, app = Path(base).resolve(), Path(app).resolve()
    desktop.require(not app.is_relative_to(base) and not base.is_relative_to(app), 'Baseline and target overlap')
    desktop.require(app.is_dir(), 'Stage the target installation before finishing')
    desktop.SOURCE_SKIP = desktop.SOURCE_SKIP | desktop.MUTABLE
    # The exact upstream archive and patch are retained. Expanded pristine and
    # patched trees (including the same large upstream test dataset twice) and
    # compiler products are regenerated by build_muscle_windows.py.
    source = desktop.build_source_archive(app, base, exclude_relative=tuple(
        'vendor-expanded/muscle-5.3/'+name for name in ('source','build-source','build-linux','build-windows')))
    desktop.VERSION = VERSION
    files = desktop.write_manifest(app)
    manifest_path = app/'manifest.json'
    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    manifest['expansion_packs'] = list(PACKS)
    manifest['pack_metadata'] = 'sha256-pinned-workbench-schema-v1'
    manifest_path.write_text(json.dumps(manifest, indent=2)+'\n', encoding='utf-8')
    result = {'version': VERSION, 'files': len(files)+1, 'source_bytes': source.stat().st_size, 'source_sha256': desktop.sha(source)}
    if output:
        output = Path(output).resolve()
        desktop.require(not output.is_relative_to(app), 'ZIP must be outside the installation')
        desktop.archive(output, [*files, manifest_path], app)
        result.update(path=str(output), bytes=output.stat().st_size, sha256=desktop.sha(output))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--base-root', type=Path, required=True)
    parser.add_argument('--app-root', type=Path, required=True)
    parser.add_argument('--output', type=Path)
    parser.add_argument('--stage-only', action='store_true', help='Prepare runtime for testing; no source ZIP or release inventory yet')
    parser.add_argument('--finish', action='store_true', help='Freeze a previously staged, validated runtime')
    args = parser.parse_args()
    base, app = args.base_root.resolve(), args.app_root.resolve()
    if not args.finish:
        catalog = stage(base, app)
        print(json.dumps({'packs': len(catalog['packs']), 'tasks': len(catalog['tools'])}))
    if not args.stage_only:
        print(json.dumps(finish(base, app, args.output), indent=2))


if __name__ == '__main__':
    main()
