/* Native Workbench contributors, MIT. Unmodified upstream scientific programs. */
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import java.util.zip.*;
import com.google.gson.*;

public final class WorkbenchSnpEff {
    static final String VERSION="5.4c", RESOURCE="native-workbench-snpeff-database-v1";
    static final Gson JSON=new GsonBuilder().setPrettyPrinting().create();
    static final long MAX_RESOURCE=64L*1024*1024*1024, MAX_MEMBER=32L*1024*1024*1024;
    static Path eff,sift,baseConfig,out,work; static int heap; static List<List<String>> commands=new ArrayList<>();
    static Map<String,Object> provenance=new LinkedHashMap<>();
    static void require(boolean test,String error)throws IOException{if(!test)throw new IOException(error);}
    static String id(String s)throws IOException{require(s.matches("[A-Za-z][A-Za-z0-9_.-]{0,99}"),"Assembly/database ID must start with a letter and contain only letters, digits, dot, underscore or dash (maximum 100 characters)");return s;}
    static int integer(String s,int lo,int hi)throws IOException{try{int n=Integer.parseInt(s);if(n>=lo&&n<=hi)return n;}catch(Exception ignored){}throw new IOException("Expected integer "+lo+".."+hi);}
    static String sha(Path p)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=Files.newInputStream(p)){byte[] b=new byte[1048576];int n;while((n=in.read(b))!=-1)d.update(b,0,n);}return HexFormat.of().formatHex(d.digest());}
    static void json(Path p,Object value)throws IOException{Files.writeString(p,JSON.toJson(value)+"\n",StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);}
    static BufferedReader reader(Path p)throws IOException{BufferedInputStream raw=new BufferedInputStream(Files.newInputStream(p));raw.mark(2);int a=raw.read(),b=raw.read();raw.reset();return new BufferedReader(new InputStreamReader(a==31&&b==139?new GZIPInputStream(raw):raw,StandardCharsets.UTF_8.newDecoder()));}
    static Path stage(String source,String name)throws Exception{Path src=Paths.get(source).toRealPath(),dst=work.resolve(name);require(Files.isRegularFile(src),"Input is not a regular local file");String before=sha(src);try(InputStream in=Files.newInputStream(src);OutputStream o=Files.newOutputStream(dst,StandardOpenOption.CREATE_NEW)){in.transferTo(o);}require(before.equals(sha(dst))&&before.equals(sha(src)),"Input changed while staging: "+source);provenance.put(name,Map.of("source",src.toString(),"sha256",before,"bytes",Files.size(src)));return dst;}
    static Path plain(String source,String name)throws Exception{Path original=stage(source,name+".selected");Path p=work.resolve(name);try(BufferedReader r=reader(original);BufferedWriter w=Files.newBufferedWriter(p,StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW)){String line;while((line=r.readLine())!=null){w.write(line);w.write('\n');}}return p;}
    static Path config(String genome)throws Exception{Path c=work.resolve("snpEff.config");StringBuilder original=new StringBuilder("data.dir = ./data/\n");for(String line:Files.readAllLines(baseConfig))if(line.trim().startsWith("codon."))original.append(line).append("\n");Files.writeString(c,original.toString()+genome+".genome : "+genome+"\n",StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);return c;}
    static void codes(String genome,String code,Map<String,String> overrides)throws Exception{
        Set<String> allowed=new HashSet<>();for(String line:Files.readAllLines(baseConfig)){String trimmed=line.trim();if(trimmed.startsWith("codon."))allowed.add(trimmed.substring(6).split("[\\s:=]",2)[0]);}
        require(allowed.contains(code),"Unsupported database genetic code");StringBuilder text=new StringBuilder(genome+".codonTable : "+code+"\n");
        for(var e:overrides.entrySet()){require(e.getKey().matches("[A-Za-z0-9_][A-Za-z0-9_.-]{0,149}")&&allowed.contains(e.getValue()),"Unsafe/unknown per-contig genetic-code override");text.append(genome).append(".").append(org.snpeff.interval.Chromosome.simpleName(e.getKey())).append(".codonTable : ").append(e.getValue()).append("\n");}
        Files.writeString(work.resolve("snpEff.config"),text.toString(),StandardOpenOption.APPEND);
    }
    static void run(Path jar,List<String> args,Path stdout)throws Exception{
        Path java=Paths.get(System.getProperty("java.home"),"bin",System.getProperty("os.name").startsWith("Windows")?"java.exe":"java");
        List<String> cmd=new ArrayList<>(List.of(java.toString(),"-Xms64m","-Xmx"+heap+"m","-XX:+ExitOnOutOfMemoryError","-XX:+DisableAttachMechanism","-XX:-UsePerfData","-Djava.awt.headless=true","-Dfile.encoding=UTF-8","-Duser.language=en","-Duser.country=US","-Djava.io.tmpdir="+work,"-jar",jar.toString()));cmd.addAll(args);commands.add(cmd);
        ProcessBuilder pb=new ProcessBuilder(cmd).directory(work.toFile()).redirectError(ProcessBuilder.Redirect.appendTo(out.resolve("upstream.log").toFile()));
        if(stdout==null)pb.redirectOutput(ProcessBuilder.Redirect.appendTo(out.resolve("upstream.log").toFile()));else pb.redirectOutput(stdout.toFile());
        for(String key:List.of("JAVA_TOOL_OPTIONS","JDK_JAVA_OPTIONS","_JAVA_OPTIONS","CLASSPATH"))pb.environment().remove(key);
        int status=pb.start().waitFor();require(status==0,"Upstream command failed (exit "+status+"); inspect upstream.log");
    }
    // SnpEff's Config treats drive-prefixed Windows data paths as relative.
    // Child cwd and the generated config's parent are both this private work directory.
    static List<String> effArgs(String op,String genome)throws Exception{return new ArrayList<>(List.of(op,"-noLog","-nodownload","-c",config(genome).toString(),"-dataDir","data"));}
    static final class Ref implements AutoCloseable {
        final RandomAccessFile file; final Map<String,long[]> contigs=new LinkedHashMap<>(); final Set<String> normalized=new HashSet<>();
        Ref(Path p)throws Exception{file=new RandomAccessFile(p.toFile(),"r");String name=null,line;long length=0,start=0,width=0,bytes=0;boolean shortLine=false;
            while(true){long offset=file.getFilePointer();line=file.readLine();if(line==null)break;if(line.startsWith(">")){if(name!=null){require(length>0,"Empty reference contig");contigs.put(name,new long[]{length,start,width,bytes});}name=line.substring(1).split("\\s+",2)[0];require(!name.isEmpty()&&!contigs.containsKey(name),"Duplicate/empty reference contig");require(normalized.add(org.snpeff.interval.Chromosome.simpleName(name)),"Reference contig names collide after upstream SnpEff normalization: "+name);length=0;width=0;shortLine=false;}
                else{require(name!=null&&line.matches("[ACGTNRYKMSWBDHVacgtnrykmswbdhv]+"),"Reference must be plain, regular-wrapped DNA FASTA");require(!shortLine,"Reference FASTA has an internal short line");if(width==0){start=offset;width=line.length();bytes=file.getFilePointer()-offset;}else{require(line.length()<=width,"Reference FASTA line widths differ");if(line.length()<width)shortLine=true;else require(file.getFilePointer()-offset==bytes,"Reference FASTA line endings differ");}length+=line.length();}}
            require(name!=null&&length>0,"Empty reference FASTA");contigs.put(name,new long[]{length,start,width,bytes});}
        void check(String chr,long pos,String allele)throws Exception{long[] c=contigs.get(chr);require(c!=null,"VCF contig is absent from database reference: "+chr);require(pos>0&&pos+allele.length()-1<=c[0],"Variant extends beyond reference contig");for(int i=0;i<allele.length();i++){long at=pos-1+i;file.seek(c[1]+at/c[2]*c[3]+at%c[2]);require(Character.toUpperCase((char)file.read())==Character.toUpperCase(allele.charAt(i)),"VCF REF does not match selected database reference at "+chr+":"+pos);}}
        public void close()throws IOException{file.close();}
    }
    static final class Vcf {long count;String identity;String reference;boolean multi;Set<String> info=new HashSet<>();List<String> samples=new ArrayList<>();}
    static Vcf validate(Path p,Ref ref,boolean needAnn)throws Exception{
        Vcf value=new Vcf();MessageDigest digest=MessageDigest.getInstance("SHA-256");String[] columns=null;boolean first=true;Set<String> existing=new HashSet<>();
        try(BufferedReader r=reader(p)){String line;while((line=r.readLine())!=null){if(first){require(line.startsWith("##fileformat=VCFv4."),"Expected VCF4 header");first=false;}if(line.startsWith("##reference="))value.reference=line.substring(12);if(line.startsWith("##INFO=<ID=")){String key=line.substring(11).split(",",2)[0];require(value.info.add(key),"Duplicate VCF INFO header: "+key);}if(line.startsWith("##"))continue;
                if(line.startsWith("#CHROM")){require(columns==null,"Duplicate VCF column header");columns=line.split("\t",-1);require(columns.length==8||(columns.length>=10&&columns[8].equals("FORMAT")),"Malformed VCF sample columns");require(String.join("\t",Arrays.copyOf(columns,8)).equals("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"),"Malformed VCF columns");for(int i=9;i<columns.length;i++){require(!columns[i].isBlank()&&existing.add(columns[i]),"Duplicate/empty VCF sample");value.samples.add(columns[i]);}continue;}
                require(columns!=null,"VCF column header is missing");String[] f=line.split("\t",-1);require(f.length==columns.length,"VCF record columns differ from header");long pos;try{pos=Long.parseLong(f[1]);}catch(Exception e){throw new IOException("Invalid VCF position");}require(pos>0&&f[3].matches("[ACGTNacgtn]+")&&f[4].matches("[ACGTNacgtn]+(,[ACGTNacgtn]+)*"),"Only ordinary small-variant VCF alleles are supported; gVCF/symbolic alleles are not accepted");
                if(f[4].contains(","))value.multi=true;if(ref!=null)ref.check(f[0],pos,f[3]);Map<String,String> infos=new HashMap<>();if(!f[7].equals("."))for(String item:f[7].split(";",-1)){String[] bits=item.split("=",2);require(bits[0].matches("[A-Za-z_][A-Za-z0-9_.]*")&&!infos.containsKey(bits[0]),"Invalid/duplicate VCF INFO key");infos.put(bits[0],bits.length==1?"":bits[1]);}
                if(needAnn){require(infos.containsKey("ANN"),"Every input record must have a SnpEff ANN annotation");for(String annotation:infos.get("ANN").split(",")){String[] a=annotation.split("\\|",-1);require(a.length>=16&&Set.of("HIGH","MODERATE","LOW","MODIFIER").contains(a[2]),"Malformed ANN impact annotation");}}
                for(int i=0;i<f.length;i++)if(i!=7){digest.update((i==5&&!f[i].equals(".")?new java.math.BigDecimal(f[i]).stripTrailingZeros().toPlainString():f[i]).getBytes(StandardCharsets.UTF_8));digest.update((byte)'\t');}digest.update((byte)'\n');value.count++;}}
        require(columns!=null,"VCF column header is missing");value.identity=HexFormat.of().formatHex(digest.digest());return value;
    }
    static void same(Vcf before,Vcf after)throws IOException{require(before.count==after.count&&before.samples.equals(after.samples)&&before.identity.equals(after.identity),"Annotation unexpectedly changed loci, alleles, record order, filters or genotypes");}
    static void databaseZip(Path target,Map<String,Object> meta,Map<String,Path> files)throws Exception{
        List<Map<String,Object>> inventory=new ArrayList<>();for(var e:files.entrySet())inventory.add(Map.of("path",e.getKey(),"bytes",Files.size(e.getValue()),"sha256",sha(e.getValue())));meta.put("files",inventory);
        try(ZipOutputStream zip=new ZipOutputStream(Files.newOutputStream(target,StandardOpenOption.CREATE_NEW))){ZipEntry e=new ZipEntry("database.json");e.setTime(0);zip.putNextEntry(e);zip.write(JSON.toJson(meta).getBytes(StandardCharsets.UTF_8));zip.closeEntry();for(var item:files.entrySet()){e=new ZipEntry(item.getKey());e.setTime(0);zip.putNextEntry(e);try(InputStream in=Files.newInputStream(item.getValue())){in.transferTo(zip);}zip.closeEntry();}}
    }
    static Map<String,Object> resource(Path selected)throws Exception{
        Path root=work.resolve("resource");Files.createDirectory(root);
        try(ZipFile zip=new ZipFile(selected.toFile())){
            ZipEntry m=zip.getEntry("database.json");require(m!=null&&m.getSize()>0&&m.getSize()<1048576,"Not a Workbench SnpEff database resource");JsonObject meta;
            try(Reader r=new InputStreamReader(zip.getInputStream(m),StandardCharsets.UTF_8)){meta=JsonParser.parseReader(r).getAsJsonObject();}
            require(meta.get("schema").getAsString().equals(RESOURCE)&&meta.get("snpEffVersion").getAsString().equals(VERSION),"Database resource schema/SnpEff version differs");String genome=id(meta.get("assembly").getAsString());require(meta.get("annotationRelease").getAsString().matches("[A-Za-z0-9][A-Za-z0-9_. -]{0,149}"),"Invalid annotation release identity");
            Map<String,JsonObject> expected=new HashMap<>();Set<String> folded=new HashSet<>();for(JsonElement el:meta.getAsJsonArray("files")){JsonObject item=el.getAsJsonObject();String n=item.get("path").getAsString();require(n.equals("reference.fa")||n.matches("data/"+java.util.regex.Pattern.quote(genome)+"/[A-Za-z0-9_.-]+\\.bin"),"Unsafe/unrecognized database resource member: "+n);require(folded.add(n.toLowerCase(Locale.ROOT)),"Duplicate database member");require(item.get("sha256").getAsString().matches("[0-9a-f]{64}"),"Invalid database checksum");expected.put(n,item);}require(expected.size()>=2&&expected.size()<=20000&&expected.containsKey("reference.fa")&&expected.containsKey("data/"+genome+"/snpEffectPredictor.bin"),"Incomplete database inventory");
            Set<String> seen=new HashSet<>();long total=0;for(Enumeration<? extends ZipEntry> entries=zip.entries();entries.hasMoreElements();){ZipEntry e=entries.nextElement();String n=e.getName();require(seen.add(n),"Duplicate ZIP member");if(n.equals("database.json"))continue;require(!e.isDirectory()&&expected.containsKey(n),"Unlisted database member: "+n);long size=expected.get(n).get("bytes").getAsLong();require(size>=0&&size<=MAX_MEMBER&&size==e.getSize(),"Invalid database member size");total+=size;require(total<=MAX_RESOURCE,"Database exceeds 64 GiB expanded resource limit");Path dest=root.resolve(n);Files.createDirectories(dest.getParent());long wrote=0;try(InputStream in=zip.getInputStream(e);OutputStream o=Files.newOutputStream(dest,StandardOpenOption.CREATE_NEW)){byte[] b=new byte[1048576];int count;while((count=in.read(b))!=-1){wrote+=count;require(wrote<=size,"Database member exceeds declared size");o.write(b,0,count);}}require(wrote==size&&sha(dest).equals(expected.get(n).get("sha256").getAsString()),"Database checksum mismatch: "+n);}
            require(seen.size()==expected.size()+1,"Missing database member");Files.move(root.resolve("data"),work.resolve("data"));Files.move(root.resolve("reference.fa"),work.resolve("reference.fa"));return JSON.fromJson(meta,Map.class);
        }
    }
    static void build(String[] a)throws Exception{
        require(a.length==8,"Expected reference, annotation, CDS, format, assembly ID, annotation release, genetic code and mitochondrial contigs");String genome=id(a[4]),release=a[5];require(release.matches("[A-Za-z0-9][A-Za-z0-9_. -]{0,149}"),"Annotation release must be a short plain identifier");require(Set.of("gff3","gtf22").contains(a[3]),"Choose GFF3 or GTF2.2");require(Set.of("Standard","Bacterial_and_Plant_Plastid","Vertebrate_Mitochondrial").contains(a[6]),"Unsupported genetic code");
        Path ref=plain(a[0],"reference.fa"),annotation=plain(a[1],"annotation.txt"),cds=plain(a[2],"cds.fa");Map<String,String> overrides=new LinkedHashMap<>();try(Ref check=new Ref(ref)){if(!a[7].equals("none")){require(a[7].matches("[A-Za-z0-9_][A-Za-z0-9_.-]*(,[A-Za-z0-9_][A-Za-z0-9_.-]*){0,31}"),"Mitochondrial contigs must be comma-separated names or none");for(String chr:a[7].split(",")){require(check.contigs.containsKey(chr),"Selected mitochondrial contig absent from reference: "+chr);require(!overrides.containsKey(chr),"Duplicate mitochondrial contig");overrides.put(chr,"Vertebrate_Mitochondrial");}}}Path db=work.resolve("data").resolve(genome);Files.createDirectories(db);Files.copy(ref,db.resolve("sequences.fa"));Files.copy(annotation,db.resolve(a[3].equals("gff3")?"genes.gff":"genes.gtf"));Files.copy(cds,db.resolve("cds.fa"));List<String> cmd=effArgs("build",genome);codes(genome,a[6],overrides);cmd.addAll(List.of("-"+a[3],"-noCheckProtein","-maxErrorRate","0.0",genome));run(eff,cmd,null);
        Map<String,Path> files=new TreeMap<>();files.put("reference.fa",ref);try(var paths=Files.list(db)){paths.filter(p->p.getFileName().toString().endsWith(".bin")).forEach(p->files.put("data/"+genome+"/"+p.getFileName(),p));}require(files.containsKey("data/"+genome+"/snpEffectPredictor.bin"),"Upstream database build did not produce predictor");Map<String,Object> meta=new LinkedHashMap<>();meta.put("schema",RESOURCE);meta.put("snpEffVersion",VERSION);meta.put("assembly",genome);meta.put("annotationRelease",release);meta.put("geneticCode",a[6]);meta.put("codonOverrides",overrides);meta.put("origin","local-build");meta.put("sourceInputs",new LinkedHashMap<>(provenance));meta.put("validation","Upstream supplied CDS comparison at maxErrorRate=0; no separate protein comparison. Coverage is the supplied CDS set, not a completeness guarantee.");databaseZip(out.resolve("database.zip"),meta,files);provenance.put("database",meta);provenance.put("databaseSha256",sha(out.resolve("database.zip")));
    }
    static void annotate(String[] a)throws Exception{
        require(a.length==4,"Expected VCF, database ZIP, upstream/downstream length and splice-site size");Path input=plain(a[0],"input.vcf"),db=stage(a[1],"database.zip");Map<String,Object> meta=resource(db);String genome=meta.get("assembly").toString();Vcf before;try(Ref ref=new Ref(work.resolve("reference.fa"))){before=validate(input,ref,false);}require(!before.info.contains("ANN"),"Input already has ANN; remove/review old consequence annotations before reannotation");List<String> cmd=effArgs("ann",genome);String code=meta.getOrDefault("geneticCode","Standard").toString();require(meta.containsKey("codonOverrides")&&meta.get("codonOverrides") instanceof Map,"Resource must explicitly record per-contig genetic-code overrides");codes(genome,code,(Map<String,String>)meta.get("codonOverrides"));cmd.addAll(List.of("-noStats","-noLof","-ud",String.valueOf(integer(a[2],0,100000)),"-spliceSiteSize",String.valueOf(integer(a[3],1,20)),genome,input.toString()));Path result=out.resolve("variants.vcf");run(eff,cmd,result);Vcf after=validate(result,null,true);same(before,after);String warning="ERROR_CHROMOSOME_NOT_FOUND|ERROR_OUT_OF_CHROMOSOME_RANGE|WARNING_REF_DOES_NOT_MATCH_GENOME";try(BufferedReader r=reader(result)){String s;while((s=r.readLine())!=null)require(!s.matches(".*("+warning+").*"),"SnpEff database/reference mismatch; result is not valid");}provenance.put("database",meta);provenance.put("records",after.count);provenance.put("allLociAllelesAndGenotypesRetained",true);
    }
    static void local(String[] a)throws Exception{
        require(a.length==4,"Expected input VCF, local annotation VCF, INFO fields and assembly identity");id(a[3]);require(a[2].matches("[A-Za-z_][A-Za-z0-9_.]*(,[A-Za-z_][A-Za-z0-9_.]*){0,31}"),"Choose up to 32 comma-separated INFO IDs");Path input=plain(a[0],"input.vcf"),db=plain(a[1],"annotation.vcf");Vcf before=validate(input,null,false),source=validate(db,null,false);require(!before.multi&&!source.multi,"Local VCF annotation requires normalized biallelic records in both files; split/normalize them first");require(before.reference==null||source.reference==null||before.reference.equals(source.reference),"VCF reference header identities differ; select matching assembly resources");for(String key:a[2].split(",")){require(source.info.contains(key),"Selected INFO header is absent from annotation VCF: "+key);require(!before.info.contains("DB_"+key),"Input already contains output INFO field DB_"+key);}Path result=out.resolve("variants.vcf");run(sift,List.of("annotate","-noLog","-noDownload","-noId","-info",a[2],"-name","DB_",db.toString(),input.toString()),result);Vcf after=validate(result,null,false);same(before,after);provenance.put("declaredAssembly",a[3]);provenance.put("assemblyVerification","User-declared matching assembly; matching CHROM, POS, REF and ALT, no liftover or sequence-reference verification in this operation");provenance.put("records",after.count);provenance.put("infoFields",a[2]);provenance.put("allLociAllelesAndGenotypesRetained",true);
    }
    static void filter(String[] a)throws Exception{
        require(a.length==2&&Set.of("HIGH","MODERATE","LOW","MODIFIER").contains(a[1]),"Choose one exact ANN impact class");Path input=plain(a[0],"input.vcf");Vcf before=validate(input,null,true);String expression="ANN[*].IMPACT = '"+a[1]+"'";Path result=out.resolve("variants.vcf");run(sift,List.of("filter","-noLog","-noDownload",expression,input.toString()),result);Vcf after=validate(result,null,true);require(after.count<=before.count,"Filtered output count exceeds input");provenance.put("recordsBefore",before.count);provenance.put("records",after.count);provenance.put("expression",expression);provenance.put("selection","Entire VCF records retained when any allele/transcript annotation has the selected exact impact. All original ALT alleles and sample genotypes remain; no pathogenicity assertion.");
    }
    public static void main(String[] args){try{require(args.length>=6,"Expected operation, SnpEff JAR, SnpSift JAR, config asset, result directory, heap and operation inputs");String op=args[0];eff=Paths.get(args[1]).toRealPath();sift=Paths.get(args[2]).toRealPath();baseConfig=Paths.get(args[3]).toRealPath();out=Paths.get(args[4]).toAbsolutePath();heap=integer(args[5],512,65536);Files.createDirectories(out);work=out.resolve("work");Files.createDirectory(work);provenance.put("schema","native-workbench-snpeff-run-v1");provenance.put("operation",op);provenance.put("upstreamVersion",VERSION);provenance.put("javaVersion",System.getProperty("java.version"));provenance.put("network","SnpEff/SnpSift downloads, usage reporting and update checks explicitly disabled");String[] rest=Arrays.copyOfRange(args,6,args.length);switch(op){case "build-database":build(rest);break;case "annotate":annotate(rest);break;case "annotate-local":local(rest);break;case "filter-impact":filter(rest);break;default:throw new IOException("Unknown operation");}provenance.put("commands",commands);provenance.put("success",true);json(out.resolve("provenance.json"),provenance);System.out.println("SnpEff/SnpSift completed: "+op);}catch(Exception e){try{if(out!=null){Files.deleteIfExists(out.resolve("variants.vcf"));Files.deleteIfExists(out.resolve("database.zip"));if(!Files.exists(out.resolve("commands-failed.json")))json(out.resolve("commands-failed.json"),commands);}}catch(Exception ignored){}System.err.println("SnpEff Workbench: "+e.getMessage());System.exit(1);}}
}
